# syntax=docker/dockerfile:1

ARG GO_VERSION=1.24

FROM mcr.microsoft.com/devcontainers/go:${GO_VERSION}-bookworm

# Set development environment
ENV GO_ENV=development

# Set working directory
WORKDIR /usr/src/app

# Install CompileDaemon for live-reloading during development
RUN go install github.com/githubnemo/CompileDaemon@latest

# Expose API port
EXPOSE 8080

# Use CompileDaemon to run the application with live-reload
CMD ["CompileDaemon", "--build=go build -o ./tmp/main ./cmd/app/main.go", "--command=./tmp/main"]