# syntax=docker/dockerfile:1

ARG GO_VERSION=1.24

FROM mcr.microsoft.com/devcontainers/go:${GO_VERSION}-bookworm

# Set development environment
ENV GO_ENV=development

# Set working directory
WORKDIR /usr/src/app

# Install Air for live-reloading during development
RUN go install github.com/air-verse/air@latest \
    && air init

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Install dependencies
RUN go mod download

# Copy the rest of the application code
COPY . .

# Expose API port
EXPOSE 8080

# Use Air to run the application with live-reload
CMD ["air"]