### Variáveis globais
@baseUrl = http://localhost:8080
@contentType = application/json


### Account
@accountApiKey = {{createAccount.response.body.api_key}}

### Criar uma nova conta
# @name createAccount
POST {{baseUrl}}/accounts
Content-Type: {{contentType}}

{
    "name": "John Doe",
    "email": "john@example_2.com"
}

### Buscar conta por API Key
###(Ex: d2454cbc2c3eb50eb5d8ec1cd581f847)
GET {{baseUrl}}/accounts
X-API-Key: {{accountApiKey}}


### Invoice
@invoiceId = {{createInvoice.response.body.id}}

### Criar uma nova fatura
# @name createInvoice
POST {{baseUrl}}/invoices
X-API-Key: {{accountApiKey}}
Content-Type: {{contentType}}

{
    "amount": 60000,
    "description": "30 Pacote de Café 500g",
    "payment_type": "credit_card",
    "card_number": "1234567890123456",
    "cvv": "123",
    "expiry_month": 12,
    "expiry_year": 2025,
    "card_holder_name": "John Doe"
}

### Buscar fatura pelo ID da fatura
###(Ex: b4c905ed-350f-461a-9154-6d56556eacff)
GET {{baseUrl}}/invoices/{{invoiceId}}
X-API-Key: {{accountApiKey}}

### Buscar faturas pelo ID da conta
GET {{baseUrl}}/invoices
X-API-Key: {{accountApiKey}}
