apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-frontend
  labels:
    app: next-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-frontend
  template:
    metadata:
      labels:
        app: next-frontend
    spec:
      nodeSelector:
        workload: frontend
      containers:
      - name: next-frontend
        image: next-frontend:dev
        ports:
        - containerPort: 3000
        env:
          - name: GATEWAY_API_URL
            value: "http://gateway-api:8080"
          - name: HOST
            value: "0.0.0.0"
        volumeMounts:
        - name: source-code
          mountPath: /usr/src/app
      volumes:
      - name: source-code
        hostPath:
          path: /workspace/next-frontend
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: next-frontend
spec:
  type: LoadBalancer
  selector:
    app: next-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000