# For more information, see https://kind.sigs.k8s.io/
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /workspace/go-gateway-api
    containerPath: /workspace/go-gateway-api
- role: worker
  extraMounts:
  - hostPath: /workspace/go-gateway-api
    containerPath: /workspace/go-gateway-api
- role: worker
  extraMounts:
  - hostPath: /workspace/go-gateway-api
    containerPath: /workspace/go-gateway-api